### ISSUE TITLE
isWebGL defined in multiple places

### ISSUE THREAD

**Issue by tsherif** [uber/luma.gl#1048]
And some of them don't work. This is the correct one: https://github.com/uber/luma.gl/blob/master/modules/webgl/src/webgl-utils/webgl-checks.js#L12-L19

Remove all other definitions of `isWebGL` and import this one for those tests.

**Comment by ibgreen** [comment]
NOTE: Some duplicate definitions might be extraneous but some are intentional. E.g:

* shadertools is a textual library that does not depend on the webgl module.

**Comment by tsherif** [comment]
If that function is need so broadly, it probably shouldn't be in webgl. How about we move it into core/utils?

**Comment by 1chandu** [comment]
I did a grep and and following modules use it, some of them define locally and use it.

`webgl` -> defines and and exports, this is the correct version.
`core` -> imports it from `webgl` and re exports it.

these are the other modules that define and use it with in that module:
`shadertools`
`webgl-state-tracker`
`webgl2-polyfill`

These modules are completely independent and doesn't depend on any other module.
One other option is to move this definition to `@luma.gl/constants` and make all other modules import it, any other suggestions?

**Comment by ibgreen** [comment]
> If that function is need so broadly, it probably shouldn't be in webgl. How about we move it into core/utils?

Well that is exactly the thing. core depends on webgl and shadertools, not the other way.

**Comment by tsherif** [comment]
Should we have a separate `utils` module for small, widely-used functions like this?

**Comment by ibgreen** [comment]
That is certainly an option, however I can say that the current design is intentional:

* I believe in having independent modules that are designed to work well together. 
* I think a small set of duplication is reasonable. isWebGL is a trivial method.

Certainly if the duplication grows beyond a certain level, it is worth a discussion for that particular module. My first instinct would be to try to reduce duplication rather than create a "common ancestor"

FWIW, I don't think adding functions to @luma.gl/constants makes sense either.

In this case, I'd just fix the function in the various places.

**Comment by tsherif** [comment]
> I think a small set of duplication is reasonable. isWebGL is a trivial method.

I agree that duplication can be reasonable, but this is a case where it introduced a subtle failure (the constant inlining has been in there for 2 months, and we just spotted this problem now). I think we should try to prevent that from happening again when the solution is relatively simple.

We could potentially add more tests to cover all the versions of this function, but I think consolidating into a utils module is probably the lowest-maintenance approach.

**Comment by ibgreen** [comment]
Understood. It is your call. I will offer these final thoughts:

* The plan has been to gradually break out shadertools, polyfills, state-tracker into their own repos (which is why this function was duplicated in the first place). 
* Once they are broken out, I don't see that we want them to depend on a micro module from luma.gl just to define a trivial webgl check. So making them share this function again would be a temporary change until we break them out?
* We would need to keep additions to the common root module very disciplined so we don't allow the different modules to effectively become dependent on each other again.

**Comment by tsherif** [comment]
I think that makes sense. When we start breaking things out, we can take a look at how to refactor.

> We would need to keep additions to the common root module very disciplined so we don't allow the different modules to effectively become dependent on each other again.

Totally agree. I imagine this would just be for very small, generic functions.

**Comment by 1chandu** [comment]
Another related question : 

The method defined in `webgl` modules checks for following : 
 1. `is it WebGL2RenderingContext` , 
 2. `context.TEXTURE_BINDING_3D` is defined.

Current issue with Safari might go away by replacing `gl.TEXTURE_BINDING_3D` with `glAlias.TEXTURE_BINDING_3D` as a workaround for bable plugin replacing the strings.

Some versions of `isWebGL2` defined only perform **2** above. My understanding this is intentional, as **1** would require access to `global` from `webgl/src/utils/globals`.

**Comment by 1chandu** [comment]
Closing remaining work is tracked here: https://github.com/uber/luma.gl/issues/1055
