### ISSUE TITLE
IE11: indexed drawing broken on platforms that don't support VAOs

### ISSUE THREAD

**Issue by CaitlinWeb** [uber/luma.gl#1208]
See thorough bug report in comment: https://github.com/uber/luma.gl/issues/1208#issuecomment-530898902

-----------------------------
IE11 seems to draw properly with deck.gl's `LineLayer` but not with the `PathLayer`. It appears that a call to `drawArraysInstanced` in the `PathLayer` even though it's drawing an indexed mesh. Investigate whether luma is incorrectly selecting between instanced indexed and non-indexed meshes, or if the problem is in IE itself.

--------------------------------------------
### Actual Result 
Lines are drawn but then disappear with this error appearing in console:
> WEBGL11037: INVALID_OPERATION: drawArraysInstancedANGLE: Insufficient buffer size

#### Expected Result
WebGL2 will work as expected, lines are drawn and persist without errors.

#### Reproduce Steps
I'm using deck.gl version 7.2.0 which uses luma.gl version 7.2.0.

You can see it happening with this example in IE11: https://luma.gl/#/examples/core-examples/instancing

Lines may appear briefly before disappearing, or you may not be able to see them at all (most likely when the error is encountered too quickly for the lines to render).

It's been mentioned before (#976, https://github.com/uber/deck.gl/issues/2070, https://github.com/uber/deck.gl/issues/2267) but as far as I can tell it's still an issue. 

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by CaitlinWeb** [comment]
@ibgreen @Pessimistress @tsherif @1chandu Can any of you help with this? I have a deadline coming up and want to get this working in IE11 100%. 

Perhaps it's a simple fix, seems like the buffer size is assigned an invalid or incorrect value. (Of course, I don't know how it all works...)

**Comment by ibgreen** [comment]
@CaitlinWeb Thanks for reporting and apologies for slow reply.

Unfortunately, in general, recent versions of luma.gl does not work very well on IE11 (we just haven't found the time and priority to address it).

Therefore, before we start, are things working well for you otherwise? Or are you just using the Webgl2 polyfills?

I am trying to assess if this is just a matter of fixing one thing (we can certainly look at this particular failure), or if we need to temper your expectations.

**Comment by tsherif** [comment]
@CaitlinWeb if you aren't using newer features of deck, does using an older version help? https://www.npmjs.com/package/deck.gl?activeTab=versions
Maybe try 6.4.9.

There appears to be a bug in the IE implementation of the instanced arrays extension, and Microsoft is no longer making non-security updates to IE, but I'm wondering if it's a more recent update in deck or luma that started hitting that bug.

**Comment by CaitlinWeb** [comment]
@ibgreen Unfortuately we do need to support IE11, but it's been working well so far for everything but the paths. The paths do show up occasionally for a brief moment before the error breaks it, so it's hopefully just an issue with PathLayer or, more likely, the WebGL2 polyfill.

Good to know that IE11 is not fully supported with version 7, though.

---

@tsherif I'll try 6.4 with LineLayer and see if I encounter the error. If anything it may give you a clue what changed between versions that caused the error, if the earlier version works.

**Comment by CaitlinWeb** [comment]
@ibgreen @tsherif So change of plans, I decided to just try using LineLayers in place of PathLayer with deck.gl v7.2. It works fine in IE11, no error. So something PathLayer is doing specifically is triggering the error.

I also tried out using v6.4 but the same error happened with PathLayer, and LineLayer didn't work at all because of errors. 

It would be great to just use PathLayer so I hope there's a possible fix. Especially since it seems there were issues with LineLayer previously when now there aren't.

In the meanwhile, however, a note in the documentation that use of PathLayer is not supported with IE11 could be helpful to others.

**Comment by ibgreen** [comment]
As original author, I can dump some information, just in case it sheds some light:

We support two cases: 
- Browsers that allow for creation of `VertexArrayObjects` (most of them)
- Browsers that only have one default implicit `VertexArrayObject` (IE11 and older Edge)

If the first case we can modify the vertex arrays with impunity, but in the second case (IE11) our vertex arrays are "virtual" and we need to install/uninstall them just before we draw.

Therefore, I would caution against removing the check, in case another vertex array is currently active, we could clobber it. Instead we should understand when the vertex array is supposed to be installed (bind) before draw, and why this is not happening (bind broken, or not being called when it should, ...).

This functionality was written to support IE11, Edge and headless-gl and did originally work during the development of the VertexArray code, but has likely regressed due to IE11 and Edge rarely being tested.


@tsherif - Just a reminder that Khronos has a client side polyfill for VertexArrayObject (the only WebGL extension that can be polyfilled client side) but I could never get it working without bugs and its implementation was dated and hard to debug. That would have been so awesome since we could keep a single logic path in the main library (always assume we have VertexArrayObjects). That polyfill would have been the perfect complement to webgl2-polyfills.

We could even try to evolve the current code in luma.gl to an equivalent polyfill....

**Comment by etimberg** [comment]
Thanks for the extra details @ibgreen. I've opened #1238 which contains a fix for this. I believe the PR should still unbind the shared `VertexArrayObject` and I've tested that it fixes the issue in IE11. I'm not sure what the best way of writing an automated test for this fix would be.

**Comment by CaitlinWeb** [comment]
If anyone else runs into issues with IE11 after version 7.3.0 and stumbles across this, you need a VAO polyfill as well. I used https://github.com/greggman/oes-vertex-array-object-polyfill

**Comment by etimberg** [comment]
@CaitlinWeb thanks for the tip. That’s been blocking upgrading past deck.gl v7.1.x for me.
