### ISSUE TITLE
FramebufferObject is no longer exported

### ISSUE THREAD

**Issue by shaojingli** [uber/luma.gl#152]
After #136 , FramebufferObject class from the deprecated/fbo.js  that deck.gl is dependent on is no longer exported. This breaks deck.gl.

The replacement Framebuffer class is imcompatible with the previous FramebufferObject. This needs to be solved before we release a new luma.gl version

**Comment by ibgreen** [comment]
The FBO class has been deprecated for a while and was removed now - deck.gl should be updated.

For now, I tried to export Framebuffer with an extra alias as FramebufferObject to see if we can avoid updating deck.gl.

This fixes the previous crash but can't verify if this fully fixes the issue since rendering is still broken.
