### ISSUE TITLE
Model no longer auto deduces gl context if a program is supplied

### ISSUE THREAD

**Issue by Apercu** [uber/luma.gl#221]
Upon creation of deck.gl layers, the luma models are initializing with a null gl context, resulting in the failure of the webgl context assertion and the throw of an error.

**Comment by shaojingli** [comment]
might be related to https://github.com/uber/deck.gl/pull/721

**Comment by shaojingli** [comment]
No, this might not be related to uber/deck.gl#721.

This seems to be specific to the Trips problem. 

in `example/trips/trips-layer/trips-layer.js`, in `getModel()` function, `Model` is created without `gl` parameter.

**Comment by ibgreen** [comment]
OK I see the problem. The luma.gl model used to autodeduce its gl context from the Program, if supplied. 

I made changes to let the model take a list of shader modules directly (calling assembleShaders automatically) and probably disturbed this on functionality. It is not that useful anymore since I expect fewer models will be created with programs now.

@1chandu - We might want to restore this functionality with a deprecated note, or at least throw a more descriptive error. 

And maybe have a test case for it, and update the Upgrade Guide section. Let's discuss.

**Comment by ibgreen** [comment]
Fixed by #230
