### ISSUE TITLE
Create example that renders a series of frames to bitmaps to generate video clips

### ISSUE THREAD

**Issue by ibgreen** [uber/luma.gl#58]
@wwwtyro - we want to drive a render loop to generate bitmaps that we can either export one by one or (eventually) feed into a video generation tool. We could modify any existing example. For now we could use window.saveAs or a polyfill to save the bitmaps one by one.

@mikolalysenko is working on headless-gl support so eventually we will make this all work on the server but for now we can start with this in the browser.

@philogb

**Comment by wwwtyro** [comment]
@ibgreen That sounds like fun! Does it need to go directly to disk, or can it stay in memory until saved? Do you just want an example, or do you want a module that handles it + an example?

FWIW, getting that data to disk from the browser is _super_ hacky, but can be done. It'll look way different (in a good way) when we move to headless. I say this because I don't think much (if anything) from the browser implementation will transfer to a headless implementation, just so you're aware.

**Comment by wwwtyro** [comment]
@ibgreen If you want, I could set up a server/client that would send the rendered data to the server for saving/video generation. Little bit more time consuming to write, but we'd get videos out right away. Your call.

**Comment by ibgreen** [comment]
@wwwtyro 
>  If you want, I could set up a server/client that would send the rendered data to the server for saving/video generation. Little bit more time consuming to write, but we'd get videos out right away. Your call.
Yes that sounds good. Let's experiment with different approaches. I like the idea of being able to do the frame rendering both from the browser and the server, even if the implementations would end up a little different. 
Once we have good working example(s) we can think about how to package this up e.g. as some class + microserver combo to make it really easy to integrate this capability in apps.

**Comment by wwwtyro** [comment]
@ibgreen 

I've packaged up a microserver/client library that handles this process here: https://github.com/wwwtyro/canvas-video-generator

Enjoy!
