### ISSUE TITLE
Shader transpile fails handling texture sample instructions.

### ISSUE THREAD

**Issue by 1chandu** [uber/luma.gl#648]
Shader transpile not handling texture/texture2D instructions. 
We need to update unit tests to cover these cases.

#### To Do List 
  - [X] Add label and assign to milestone
  - [x] Coding
  - [x] Test

**Comment by ibgreen** [comment]
I believe the reason is that WebGL2 `texture` needs to be mapped to either `texture2D` or `textureCube` in WebGL1.

There is a note on https://luma.gl/#/documentation/developer-guide/writing-code, `GLSL Syntax Conversion Reference` section, saying that `texture` will be mapped to texture2D``

Agree that the doc should be cleaned up, it has several TBDs and we should check that implementation conforms. 

Happy to chat about ideas for how to improve the docs.
