### ISSUE TITLE
[Bug] failed to import luma.gl in a non-browser env, where `gl` is not installed

### ISSUE THREAD

**Issue by heshan0131** [uber/luma.gl#673]
in v5.3 during isorender, loading deck.gl imports luma.gl will result in error: 
3.0

Because the code here is expecting `gl` to be installed. if not, it will error out. 
https://github.com/uber/luma.gl/blob/master/modules/core/src/webgl-utils/webgl-types.js#L24-L31

Is this expected behavior? Seems odd to me

#### To Do List 
  - [x] Add FAQ entry to explain the situation
  - [x] Improve message to make clear it is not an error
  - [ ] Prevent the node error from being shown

**Comment by ibgreen** [comment]
> if not, it will error out.

depends on what you mean with "error out". luma.gl is designed so that the library can be **loaded** without problems under Node.js, however you can only actually **create WebGL contexts** under Node.js if `gl` is installed.

For typical isorender scenarios, you just need to load the library, you don't actually instantiate deck and luma on the server.

The message tries to convey this as clearly as possible. Happy to take suggestions for how to make this clearer:

```
luma.gl: WebGL contexts can not be created in Node.js since headless gl is not installed. \
If this is desired, install headless gl using "npm install gl --save-dev" or "yarn add -D gl
```

I will add this question to the new FAQ.

**Comment by 1chandu** [comment]
@heshan0131 @ibgreen , is there any action to be taken on this other than having an entry in FAQ ?

**Comment by ibgreen** [comment]
Depends...

If luma.gl doesn't behave as described, then it is a bug that should be fixed.

If the described behavior is problematic for the app, then we should discuss how we can improve it.

**Comment by heshan0131** [comment]
I see this error 
I have `import {ArcLayer} from 'deck.gl'`, It will load the library and in the console output after running `npm start` I see:
```
Cannot find module 'gl/wrap'
null

WebGL not available in Node.js, install using "npm install gl".
Cannot find module 'gl'
```

But the app still runs

**Comment by ibgreen** [comment]
Yes, it is not an error, just an explanation. 

Maybe we can change the message to make that more clear.

**Comment by ibgreen** [comment]
Yes. I believe the message has been removed in 6.2.
