### ISSUE TITLE
Shader compiler is seeing the request to enable the extension in IE11 part 2

### ISSUE THREAD

**Issue by MarcusPenn** [uber/luma.gl#793]
As previously there is an issue with IE and the shader compilers.
I found the issue when trying to render LineLayers in IE 11.
#### Actual Result
![image](https://user-images.githubusercontent.com/35596732/48767522-d530a600-ecae-11e8-9b98-2ae9bfa809cd.png)
This stops the line layer from rendering entirely.
#### Expected Result
Correct shader compilers are used resulting in the rendered layer and no error.
#### Reproduce Steps
Here is a rough code example
I forked someones codesandbox to give a quick example that should replicate the issue if done on IE:
https://codesandbox.io/s/m7vqzpr8ox?expanddevtools=1
#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by MarcusPenn** [comment]
In relation to #324

**Comment by MarcusPenn** [comment]
As a short term solution to get layers rendering on IE:

platform-defines.js within the luma shadertools lib can be modified from
`if (hasFeatures(gl, FEATURES.GLSL_FRAG_DATA) {`
to
`if (hasFeatures(gl, FEATURES.GLSL_FRAG_DATA) && !isOldIE()) {`
with the import of
`import isOldIE from '../utils/is-old-ie';`

**Comment by MarcusPenn** [comment]
@1chandu Implemented #794, it didn't fix the issue but was progress in the right direction.

One of my colleagues worked out that in the shader tests we require the GL_EXT_draw_buffers:
`// DRAW_BUFFERS => gl_FragData[] is available`
`#ifdef GL_EXT_draw_buffers`
`#extension GL_EXT_draw_buffers : require`
`#define DRAW_BUFFERS`
`#endif`

However in canCompileGLGSExtension we only do an enable on the source (webgl-info.js 69-71):
`var extensionName = feature[0];`
`var source = "#extension GL_".concat(extensionName, " : enable\nvoid main(void) {}");`
`var shader = gl.createShader(35633);`

Changing this to require as well fixes the issue:
`var source = "#extension GL_".concat(extensionName, " : require\nvoid main(void) {}");`

It might be better to pass a flag through to canCompileGLGSExtension for whether it should be enable or require.

**Comment by 1chandu** [comment]
Ok, did some experiments and updated #794 . Adding following details for the record, if we ever comeback to this : 

I have two options to fix the IE11 issue: 

1.  Change the `GL_EXT_draw_buffers` to be `enable` instead of `require` in `getVersionDefines` method, but this change is global in the sense it is going to affect all browsers.
2. Change `canCompileGLGSExtension` method to use `require` or `enable` based on passed in option,  when testing if a shader  compiles fine, this will only affect old IE browsers.

Going with option#2 given , whole point of this PR is to fix an IE specific issue. One caveat is, users will see an error in console (now that `canCompile` can result in an error) if browser supports the extension but doesn't support in shader using `#extension`. But this is still better than failing to compile an actual shader.

@MarcusPenn , will wait until you confirm this fixes your issue, thanks in advance.

**Comment by 1chandu** [comment]
@MarcusPenn  6.3.1 with fix published.
