### ISSUE TITLE
Tool to create custom geometries?

### ISSUE THREAD

**Issue by grahambates-sp** [uber/luma.gl#832]
I can use https://github.com/uber/luma.gl/blob/master/modules/core/src/geometry/cube-geometry.js as inspiration on how to create my own geometry representing a custom model (For eventual use in deckgl).

However what I am unclear on is how to actually use a 3d editor or converter to generate the indices, postions and normals that make up a 3d model if I do not want to hand code them. Can anyone advise?

**Comment by ibgreen** [comment]
> However what I am unclear on is how to actually use a 3d editor or converter to generate the indices, postions and normals that make up a 3d model if I do not want to hand code them. Can anyone advise?

For the editing, you could use any 3D design tool, e.g. [blender](https://www.blender.org/), but be aware any tool like that will have a considerable learning curve.

If you end up saving a model e.g. in OBJ format, you could use the OBJ loader in our [loaders.gl](https://github.com/uber-web/loaders.gl) module.

Note that luma.gl is more focused on visualization of data rather than "traditional" loading of 3D models (e.g. 3D game use case). That said, things are improving, we are working on glTF support in the background.
