### ISSUE TITLE
Remove pickModels?

### ISSUE THREAD

**Issue by tsherif** [uber/luma.gl#929]
@Pessimistress @ibgreen The pickModels module in luma.gl is not currently usable. You can see the issue if you modify the picking example so that objects overlap. It will return the first object drawn, rather than the nearest object.

The way it works is to traverse the list of objects, drawing each model individually, doing a readPixels, checking if anything was drawn, and returning the first one that passes: https://github.com/uber/luma.gl/blob/master/modules/core/src/core/pick-models.js#L50-L77
Aside from being incorrect, performance is terrible, since it does a readPixels after each object is drawn, which forces a CPU/GPU sync. 

We could try to fix it, but given that it isn't used in deck, and shouldn't really be used anywhere in its current state, would we be comfortable just removing it?

**Comment by tsherif** [comment]
On top of that, pickModels is currently broken in master, due to this update: https://github.com/uber/luma.gl/commit/613714feea6a5df9c28568663575a85ebafe5512#diff-702d76f0f4f1d3d4d18aa124ddb01dedL58

Since `Group.traverse` doesn't return anything anymore, `pickModels` will never return anything.

**Comment by ibgreen** [comment]
### Background

> The pickModels module in luma.gl is not currently usable.

Yes, the scenegraph traversal code was gutted during the glTF work, so something needs to be done.

> It will return the first object drawn, rather than the nearest object.

It used to picks using reverse traversal, it was a super hack, but the thinking was that if depth testing is disabled, this would lead to the correct (top most) object being picked.

> Aside from being incorrect, performance is terrible, since it does a readPixels after each object is drawn, which forces a CPU/GPU sync.

Yes the intention was always to fix this and draw all objects into the same buffer and read once, just like deck.gl does. But since we didn't use the scenegraph in the past so that it never became a priority. That priority is of course changing with our glTF push.

## Short Term Options

> We could try to fix it, but given that it isn't used in deck, and shouldn't really be used anywhere in its current state, would we be comfortable just removing it?

* Restoring it to the way it used to work would be very easy. 
* Removing the feature completely is another option, at least in the short term. 
* It is used in the picking example (planets) so we'd need to either fix that example using custom codex, or delete the example too.
*cI am not too keen on deleting examples since we don't have that many, but if we need to we can do it.

### Long Term Options

I think we should move deck.gl's picking system to luma.gl:

My observations are: 
* we have a fully developed color picking system in deck.gl that is proven and performs really well. 
* It is a significant chunk of code in deck.gl that would benefit from being cleaned up, generalized and documented.
* that system could easily be generalized and extended to handle a mix of scenegraph objects and layer instances. 
* The picking shader module is already in luma.gl, why not move the JS code that works with it there as well?
* I think it luma.gl's scenegraph system will be rather poor if it does not support picking.

**Comment by tsherif** [comment]
> It used to picks using reverse traversal, it was a super hack, but the thinking was that if depth testing is disabled, this would lead to the correct (top most) object being picked.

This would only work if the objects were depth-sorted prior to picking. So my feeling is restoring previous functionality isn't really worthwhile, since it will just go from one broken state to another. If it's considered worthwhile right now, I could take a crack at moving code from Deck.gl into Luma. Otherwise, my vote would be for removing it, including the example, since it's advertising functionality in the library that doesn't work and will cause confusion if anyone tries to use it.

**Comment by tsherif** [comment]
And regarding the number of examples in Luma, I'm hoping to add more with #928, so my contributions will be a net win for the number of examples we have 😄
